# Generated by Django 5.0.4 on 2024-04-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_id', models.CharField(max_length=255)),
                ('drive_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'MyDrive',
                'verbose_name_plural': 'MyDrives',
            },
        ),
    ]
