# Generated by Django 5.0.4 on 2024-05-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydrive',
            name='text_file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
